title: Ashi Poorey
description: Undergraduate Researcher in Astrophysics, Data Science & Computational Science
author: Ashi Poorey
email: apoorey2@illinois.edu

# Use remote theme so-simple
remote_theme: mmistakes/so-simple-theme

# Menu bar (these will show at the top)
menu:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Projects
    url: /projects

# Social links (will appear in footer)
social_links:
  - icon: github
    url: https://github.com/apoorey2
  - icon: linkedin
    url: https://www.linkedin.com/in/ashipoorey/
  - icon: file-text
    url: /assets/Ashi_Poorey_CV.pdf
