title: Ashi Poorey
description: Undergraduate Researcher in Astrophysics, Data Science & Computational Science
author:
  name: Ashi Poorey
  email: apoorey2@illinois.edu
  links:
    - title: GitHub
      url: https://github.com/apoorey2
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://www.linkedin.com/in/ashipoorey/
      icon: fab fa-linkedin
    - title: CV
      url: /assets/Ashi_Poorey_CV.pdf
      icon: far fa-file-pdf

remote_theme: mmistakes/so-simple-theme

navigation_links:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Projects
    url: /projects/

skin: "/assets/css/skins/custom.css"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
