# Basic site info
title: Ashi Poorey
description: undergraduate researcher in astrophysics & computational and data science
email: apoorey2@illinois.edu

# Use Phantom theme via GitHub Remote Theme
remote_theme: mmistakes/so-simple-theme

# Optional menu (change titles or add more pages)
menu:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research
  - title: "Projects"
    url: /projects
